#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=8b-probtest
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=06:00:00
#SBATCH --output=../output/letterstring/prob-tests/qwen3-8b_gen_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1
module load CUDA/12.8.0

source activate thesis
cd $HOME/counterfactual-reasoning/letterstring

srun python inspect_probs.py --model Qwen/Qwen3-8B --gen gen
