#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=run-pipe
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:40:00
#SBATCH --output=../output/Qwen3-8B/minimal/gen/qwen3-8b_gen_extra_analogical_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1
module load CUDA/12.8.0

source activate thesis
cd $HOME/counterfactual-reasoning/letterstring

srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-8B" --num_permuted 0 --promptstyle analogical --extra-split
srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-8B" --num_permuted 2 --promptstyle analogical --extra-split
srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-8B" --num_permuted 5 --promptstyle analogical --extra-split
srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-8B" --num_permuted 10 --promptstyle analogical --extra-split
srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-8B" --num_permuted 20 --promptstyle analogical --extra-split
srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-8B" --num_permuted symb --promptstyle analogical --extra-split
