#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=run-pipe
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00
#SBATCH --output=../output/Qwen3-14B/analogical/nogen/qwen3-14b_nogen_1_analogical_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1
module load CUDA/12.8.0

source activate thesis
cd $HOME/counterfactual-reasoning/letterstring

# qwen3-14b - gen - analogical
#srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-14B" --num_permuted 1 --promptstyle analogical
#srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-14B" --num_permuted 2 --promptstyle analogical
#srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-14B" --num_permuted 5 --promptstyle analogical
#srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-14B" --num_permuted 10 --promptstyle analogical
#srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-14B" --num_permuted 20 --promptstyle analogical
#srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-14B" --num_permuted symb --promptstyle analogical

# qwen3-14b - gen - minimal
#srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-14B" --num_permuted 1 --promptstyle minimal
#srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-14B" --num_permuted 2 --promptstyle minimal
#srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-14B" --num_permuted 5 --promptstyle minimal
#srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-14B" --num_permuted 10 --promptstyle minimal
#srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-14B" --num_permuted 20 --promptstyle minimal
#srun python eval_GPT_letterstring.py --gen gen --model "Qwen/Qwen3-14B" --num_permuted symb --promptstyle minimal

# qwen3-14b - nogen - minimal
#srun python eval_GPT_letterstring.py --gen nogen --model "Qwen/Qwen3-14B" --num_permuted 1 --promptstyle minimal
#srun python eval_GPT_letterstring.py --gen nogen --model "Qwen/Qwen3-14B" --num_permuted 2 --promptstyle minimal
#srun python eval_GPT_letterstring.py --gen nogen --model "Qwen/Qwen3-14B" --num_permuted 5 --promptstyle minimal
#srun python eval_GPT_letterstring.py --gen nogen --model "Qwen/Qwen3-14B" --num_permuted 10 --promptstyle minimal
#srun python eval_GPT_letterstring.py --gen nogen --model "Qwen/Qwen3-14B" --num_permuted 20 --promptstyle minimal
#srun python eval_GPT_letterstring.py --gen nogen --model "Qwen/Qwen3-14B" --num_permuted symb --promptstyle minimal

# qwen3-14b - nogen - analogical
srun python eval_GPT_letterstring.py --gen nogen --model "Qwen/Qwen3-14B" --num_permuted 1 --promptstyle analogical
#srun python eval_GPT_letterstring.py --gen nogen --model "Qwen/Qwen3-14B" --num_permuted 2 --promptstyle analogical
#srun python eval_GPT_letterstring.py --gen nogen --model "Qwen/Qwen3-14B" --num_permuted 5 --promptstyle analogical
#srun python eval_GPT_letterstring.py --gen nogen --model "Qwen/Qwen3-14B" --num_permuted 10 --promptstyle analogical
#srun python eval_GPT_letterstring.py --gen nogen --model "Qwen/Qwen3-14B" --num_permuted 20 --promptstyle analogical
#srun python eval_GPT_letterstring.py --gen nogen --model "Qwen/Qwen3-14B" --num_permuted symb --promptstyle analogical
