#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=14b-a-coords-symb
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=05:00:00
#SBATCH --output=../output/matrices/Qwen3-14B/analogical/qwen3-14b_coords_symb_analogical_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1
module load CUDA/12.8.0

source activate thesis
cd $HOME/counterfactual-reasoning/digit_matrices

# Analogical - 8B
#srun python eval_gpt_matprob.py --id Qwen/Qwen3-8B --user_prompt_num 4 --sys_prompt_num 1 --prob_format digits
#srun python eval_gpt_matprob.py --id Qwen/Qwen3-8B --user_prompt_num 4 --sys_prompt_num 1 --prob_format coords
#srun python eval_gpt_matprob.py --id Qwen/Qwen3-8B --user_prompt_num 4 --sys_prompt_num 1 --prob_format symb

# Analogical - 14B
#srun python eval_gpt_matprob.py --id Qwen/Qwen3-14B --user_prompt_num 4 --sys_prompt_num 1 --prob_format digits
srun python eval_gpt_matprob.py --id Qwen/Qwen3-14B --user_prompt_num 4 --sys_prompt_num 1 --prob_format coords
srun python eval_gpt_matprob.py --id Qwen/Qwen3-14B --user_prompt_num 4 --sys_prompt_num 1 --prob_format symb

# Minimal - 8B
#srun python eval_gpt_matprob.py --id Qwen/Qwen3-8B --user_prompt_num 2 --sys_prompt_num 1 --prob_format digits
#srun python eval_gpt_matprob.py --id Qwen/Qwen3-8B --user_prompt_num 2 --sys_prompt_num 1 --prob_format coords
#srun python eval_gpt_matprob.py --id Qwen/Qwen3-8B --user_prompt_num 2 --sys_prompt_num 1 --prob_format symb

# Minimal - 14B
#srun python eval_gpt_matprob.py --id Qwen/Qwen3-14B --user_prompt_num 2 --sys_prompt_num 1 --prob_format digits
#srun python eval_gpt_matprob.py --id Qwen/Qwen3-14B --user_prompt_num 2 --sys_prompt_num 1 --prob_format coords
#srun python eval_gpt_matprob.py --id Qwen/Qwen3-14B --user_prompt_num 2 --sys_prompt_num 1 --prob_format symb
