#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=run-pipe
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=../output/qwen3-8b_minimal_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1
module load CUDA/12.8.0

source activate thesis
cd $HOME/counterfactual-reasoning/letterstring

srun python eval_GPT_letterstring.py --gen nogen --model "Qwen/Qwen3-8B" --num_permuted 1 --prompstyle minimal
